### ISSUE TITLE
osx build

### ISSUE THREAD

**Issue by Tobias-Fischer** [johnwason/tesseract-robotics-superpack-feedstock#10]
Any chance to build the superpack on osx/osx-arm64? Happy to contribute towards additional packages on conda-forge if some are missing.

**Comment by johnwason** [comment]
The Tesseract upstream hasn't been ported to osx. Porting to windows took over a year and there isn't any community demand for osx support so we haven't worked on it.

**Comment by Tobias-Fischer** [comment]
Gotcha, makes sense.
