### ISSUE TITLE
Solving environment hangs when OMPL is included on Linux

### ISSUE THREAD

**Issue by johnwason** [johnwason/tesseract-robotics-superpack-feedstock#2]
If the OMPL package is included on Linux, the environment can't be solved. It hangs forever and never returns a solution. Currently, the OMPL package is using on Windows, but OMPL is built from source on Linux.

The relevant lines are:

https://github.com/johnwason/tesseract-robotics-superpack-feedstock/blob/3cbcd0de64fad93a50d42a2b5312351142b30f5a/recipe/meta.yaml#L69

https://github.com/johnwason/tesseract-robotics-superpack-feedstock/blob/3cbcd0de64fad93a50d42a2b5312351142b30f5a/recipe/meta.yaml#L103

Include the OMPL source, but only on Linux:

https://github.com/johnwason/tesseract-robotics-superpack-feedstock/blob/3cbcd0de64fad93a50d42a2b5312351142b30f5a/recipe/meta.yaml#L44

OMPL has a `package.xml` file, so it builds normally using colcon without any additional modifications.

**Comment by Tobias-Fischer** [comment]
Have you tried `conda mambabuild` to see what the issue in solving the environment with ompl is?

**Comment by johnwason** [comment]
This has been fixed in the newest version.
