### ISSUE TITLE
Use Bullet double precision floating point

### ISSUE THREAD

**Issue by johnwason** [johnwason/tesseract-robotics-superpack-feedstock#5]
Tesseract works best when Bullet is built for double precision floating point (64-bit floats) instead of the default single precision floating point (32-bit floats). The conda package for bullet that is currently used appears to use single precision floats. Bullet should either be built from source, or a double precision bullet package variant should be made available. It is currently unclear how to deal with the potential conflict between these library versions. Can double precision Bullet be given different filenames, or even better a different namespace?

**Comment by johnwason** [comment]
@wolfv @Tobias-Fischer any suggestions on how to deploy double precision versions of bullet? I have been thinking about tinkering with ~~rebasing~~ refactoring the namespace of the double precision version but haven't tried yet.

**Comment by wolfv** [comment]
Hi @johnwason it should not be a problem at all to create a variant package. One could do that for example with a different build string.

There is, in fact, an issue open https://github.com/conda-forge/bullet-feedstock/issues/39

I think what could work is to add a `conda_build_config.yaml` file in the directory (next to `meta.yaml`) with contents like:

```
BULLET_VARIANT:
- double
- float
```

And then in the recipe, we can use something like:

```
build:
  string: {{ BULLET_VARIANT}}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  script_env:
    - BULLET_VARIANT={{ BULLET_VARIANT}}
```

And then in the scripts test for BULLET_VARIANT. I at least hope that this would work :)

**Comment by johnwason** [comment]
I have a new project using Tesseract so I am back looking at this issue - 

The Ubuntu Focal package includes both the `float` and `double` libraries side by side in the same package. 

https://packages.ubuntu.com/focal/amd64/libbullet2.88/filelist

The cmake package files include two separate configurations, one for single and double precision in https://packages.ubuntu.com/focal/amd64/libbullet-dev/filelist :

```
/usr/lib/x86_64-linux-gnu/cmake/bullet/BulletConfig-float64.cmake
/usr/lib/x86_64-linux-gnu/cmake/bullet/BulletConfig.cmake
/usr/lib/x86_64-linux-gnu/cmake/bullet/UseBullet.cmake
```

The tesseract package uses the following logic to find the correct version:

```cmake
find_package(
  Bullet
  REQUIRED
  CONFIGS
  BulletConfig-float64.cmake
  BulletConfig.cmake)
if(NOT
   ${BULLET_DEFINITIONS}
   MATCHES
   ".*-DBT_USE_DOUBLE_PRECISION.*")
  message(
    WARNING "Bullet does not appear to be build with double precision, current definitions: ${BULLET_DEFINITIONS}")
endif()
```

So I think the best option is to match the Ubuntu behavior.

**Comment by johnwason** [comment]
Also I am breaking up this package, the feedstocks can be found here: https://github.com/tesseract-robotics-packaging

**Comment by Tobias-Fischer** [comment]
Note that you can find the relevant Debian patches that add a suffix to the library names in http://archive.ubuntu.com/ubuntu/pool/universe/b/bullet/bullet_2.88+dfsg-2build2.debian.tar.xz

They simply build the package twice and install all in the same installation location, as the headers are the same and the library names differ after applying their patches.

Note that the Ubuntu patches are for Bullet 2.88, while we have Bullet 3 in conda-forge, so they might need some updates. Feel free to open a PR at https://github.com/conda-forge/bullet-feedstock/

**Comment by johnwason** [comment]
I implemented bullet3 float64 by patching and building within the workspace, and statically linking the libraries. The patches from Ubuntu helped somewhat, but they renamed the libraries in a very strange way that makes it not really suitable to use. See https://github.com/johnwason/tesseract-robotics-superpack-feedstock/blob/master/recipe/bullet3_fix.patch
